feat(nano): add ecdsa-binding encrypt flag
opentdf/otdfctl pull request #360
Opened 2024-09-04 16:44 UTC by dmihalcik-virtru

- this enables the optional 'ecdsa binding' feature in nanotdf containers

2024-09-04 17:16 UTC, pflynn-virtru submitted a review, later dismissed

2024-09-04 17:16 UTC, jakedoublev commented
This looks good. Can we please add an e2e test for this functionality to verify? https://github.com/opentdf/otdfctl/blob/main/tests/encrypt-decrypt.bats#L50

2024-09-05 02:27 UTC, jrschumacher requested changes
Tests failing due to missing flag string

2024-09-05 02:27 UTC, jrschumacher commented on cmd/tdf-inspect.go
> +	} else if result.NanoHeader != nil {
@dmihalcik-virtru this is great!! Thank you.

2024-09-05 02:27 UTC, jrschumacher commented on tests/encrypt-decrypt.bats
> +  ecdsa_enabled="$(./otdfctl $HOST $WITH_CREDS inspect $OUTFILE_GO_MOD | jq .ecdsaEnabled)"
```suggestion
  ecdsa_enabled="$(./otdfctl --host $HOST --tls-no-verify $WITH_CREDS inspect $OUTFILE_GO_MOD | jq .ecdsaEnabled)"
```

2024-09-05 02:27 UTC, jrschumacher commented on tests/encrypt-decrypt.bats
> +  ./otdfctl $HOST $WITH_CREDS inspect $OUTFILE_GO_MOD
```suggestion
  ./otdfctl --host $HOST --tls-no-verify $WITH_CREDS inspect $OUTFILE_GO_MOD
```

2024-09-05 13:15 UTC, jrschumacher approved these changes

2024-09-05 13:16 UTC, merged